/** @type {import('tailwindcss').Config} */

module.exports = {
  darkMode: "class",
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        theme: {
          primaryBackground: "var(--theme-primaryBackground)",
          secondaryBackground: "var(--theme-secondaryBackground)",
          tertiaryBackground: "var(--theme-tertiaryBackground)",
          chatBackground: "var(--theme-chatBackground)",
          primaryText: "var(--theme-primaryText)",
          secondaryText: "var(--theme-secondaryText)",
          chatDivider: "var(--theme-chatDivider)",
          modalBorder: "var(--theme-modalBorder)",
          calendarMarkings: "var(--theme-calendarMarkings)",
          onboardBackground: "var(--theme-onboardBackground)",
          emptyEvent: "var(--theme-emptyEvent)",
          footerBackground: "var(--theme-footerBackground)",
          sidebarBackground: "var(--theme-sidebarBackground)",
          sidebarDivider: "var(--theme-sidebarDivider)",
          sidebarHighlight: "var(--theme-sidebarHighlight)",
          buttonDisable: "var(--theme-buttonDisable)",
          buttonDisableText: "var(--theme-buttonDisableText)",
          buttonEnable: "var(--theme-buttonEnable)",
          error: "var(--theme-error)",
          welcomeColor: "var(--theme-welcomeColor)",
          welcomeProfile: "var(--theme-welcomeProfile)",
          sidebarColor: "var(--theme-sidebarColor)",
          placeholder: "var(--theme-placeholder)",
          subtitle: "var(--theme-subtitle)",
          dropdown: "var(--theme-dropdown)",
          description: "var(--theme-description)",
          profileColor: "var(--theme-profileColor)",
          homeToggle: "var(--theme-homeToggle)",
          chips_home: "var(--theme-chips_home)",
          pricingBackground: "var(--theme-pricingBackground)",
        },
      },
      fontFamily: {
        inter: ["Inter"],
        "familjen-grotesk": ['"Familjen Grotesk"', "sans-serif"],
      },
      fontWeight: {
        extralight: 300,
        light: 300,
        normal: 400,
        medium: 500,
        semibold: 600,
        bold: 700,
        extrabold: 800,
      },
      screens: {
        xs: "470px",
        xl: "1150px",
        xxl: "1400px",
      },

      spacing: {
        "full-minus-60": "calc(100hw - 120px)",
        "left-banner-width": "calc(100vw - 88px)",
        "full-minus-120": "calc(100vw - 72px)",
        "full-minus-12": "calc(100% - 13px)",
        "full-minus-80": "calc(100vw - 80px)",
        "full-height-36": "calc(100vh - 36px)",
        "full-height-96": "calc(100vh - 110px)",
        "full-height-70": "calc(100vh - 70px)",
        "full-height-64": "calc(100vh - 65px)",
        "full-height-48": "calc(100vh - 48px)",
        "full-height-56": "calc(100vh - 56px)",
        "full-height-84": "calc(100vh - 85px)",
        "full-height-88": "calc(100vh - 88px)",
        "full-height-40": "calc(100vh - 40px)",
        "full-height-160": "calc(100vh - 170px)",
        "page-chat-screen": "calc(100vh - 130px)",
        "full-minus-64": "calc(100vw - 72px)",
        "full-minus-44": "calc(100vw - 44px)",
        "full-minus-250": "calc(100vw - 250px)",
        "full-minus-380": "calc(100vw - 630px)",
        "full-minus-68": "calc(100% - 68px)",
        76: "305px",
        "72px": "72px",
        "88px": "350px",
        90: "360px",
        "90%": "90%",
        "bottom-sheet": "27%",
        "30%": "30%",
        xxs: "0.7rem",
        "20px": "80px",
      },
    },
  },
  plugins: [
    function ({ addComponents }) {
      addComponents({
        ".custom-checkbox": {
          position: "relative",
          flexShrink: "0",
          height: "1rem",
          width: "1rem",
          appearance: "none",
          borderRadius: "0.125rem",
          borderWidth: "2px",
          borderStyle: "solid",
          borderColor: "var(--theme-primaryText)",
          backgroundColor: "transparent",
          cursor: "pointer",
          "&:checked": {
            borderColor: "var(--theme-primaryText)",
            backgroundColor: "var(--theme-tertiaryBackground)",
          },
          "&:checked::after": {
            content: '""',
            position: "absolute",
            left: "4px",
            bottom: "3px",
            height: "10px",
            width: "6px",
            transform: "rotate(45deg)",
            border: "2px solid",
            borderColor:
              "transparent transparent var(--theme-tertiaryBackground) var(--theme-tertiaryBackground)",
            borderLeft: "none",
            borderTop: "none",
          },
        },
      });
    },
  ],
};
